fix: remove unused vars that break clang build
Since -Werror is enabled, these 2 warnings from clang 19 get promoted to
errors and fail the build. The variables `total_sent` and `processed`
are not used "meaningfully", according to clang. `processed++` doesn't
count. It is surprising to me, but I guess it makes sense as a warning.

If you add something like printf("processed = %d\n", processed), the
error goes away.

To reproduce:

  cmake .. -DCMAKE_C_COMPILER=clang
  make -j(nproc)

The errors themselves:

[ 10%] Building C object CMakeFiles/NxLite.dir/src/http.c.o
[ 20%] Building C object CMakeFiles/NxLite.dir/src/worker.c.o
/home/antharas/code/NxLite/src/worker.c:397:9: error: variable 'processed' set but not used [-Werror,-Wunused-but-set-variable]
  397 |     int processed = 0;
      |         ^
/home/antharas/code/NxLite/src/http.c:561:16: error: variable 'total_sent' set but not used [-Werror,-Wunused-but-set-variable]
  561 |         size_t total_sent = 0;
      |                ^
1 error generated.
make[2]: *** [CMakeFiles/NxLite.dir/build.make:107: CMakeFiles/NxLite.dir/src/worker.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [CMakeFiles/NxLite.dir/build.make:121: CMakeFiles/NxLite.dir/src/http.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:88: CMakeFiles/NxLite.dir/all] Error 2
make: *** [Makefile:136: all] Error 2